### ISSUE TITLE
Relationship FU Plan: John Murphy

### ISSUE THREAD

**Issue by jaahmuhl** [promazo/100k-Mentor-Challenge-Outreach#135]
**User Story / Problem / Details**
The Content Editor is in charge of ensuring the initial relationship we foster with an interviewee does not decay over time for interviewees that we designate as important. As a result we want to follow a process that allows us to interact and build a relationship with the interviewee over time. The final step of the process should be focused on how connect with an interviewee over multiple interactions and over the course of a year.

**Technical Definition of Done**
Complete all steps in the process

**Definition of Ready**
All of the steps in the process have been approved by Brett 

**Process**
- [ ] Thank you note to the participant
- [ ] Quick clip (30s) that shows the interviewee some of the raw footage/a particularly interesting part of the discussion
- [ ] ID potential contacts
- [ ] Formulate ask
- [ ] Create a Relationship Action Plan

**Comment by carolineradke** [comment]
Hi John, we wanted to reach out and thank you again for participating in our Executive Interview Series.

During our discussion, we had the privilege of hearing you speak about your early career and the qualities leaders such as yourself look for in students. Your insight into Coca-Cola's effective marketing campaigns, as well as the impact that Share-A-Coke has had in the Indian market were truly captivating. Both the Promazo team and our student audience will be excited to learn from you and your experiences.

Attached is a short clip from the interview that we found particularly interesting. The points you made on Coca-Cola's strong focus on their consumer and building relationships were insightful because they show how a personalized campaign such as Share-A-Coke can be beneficial in breaking into a very difficult market, like India.

We thank you for your time and meaningful conversation. We look forward to staying in contact with you.

**Comment by carolineradke** [comment]
CLIP:

15:42-16:28

**Comment by carolineradke** [comment]
https://docs.google.com/document/d/1B1oICz0Munlq5QogIBbE6uRlbsSrBWpf0fGVXS-D5Bg/edit

Plan
