### ISSUE TITLE
Relationship FU Plan: Nigel Murtagh

### ISSUE THREAD

**Issue by jaahmuhl** [promazo/100k-Mentor-Challenge-Outreach#137]
**User Story / Problem / Details**
The Content Editor is in charge of ensuring the initial relationship we foster with an interviewee does not decay over time for interviewees that we designate as important. As a result we want to follow a process that allows us to interact and build a relationship with the interviewee over time. The final step of the process should be focused on how connect with an interviewee over multiple interactions and over the course of a year.

**Technical Definition of Done**
Complete all steps in the process

**Definition of Ready**
All of the steps in the process have been approved by Brett 

**Process**
- [ ] Thank you note to the participant
- [ ] Quick clip (30s) that shows the interviewee some of the raw footage/a particularly interesting part of the discussion
- [ ] ID potential contacts
- [ ] Formulate ask
- [ ] Create a Relationship Action Plan

**Comment by carolineradke** [comment]
Hi Nigel, we wanted to reach out and thank you again for participating in our Executive Interview Series.

During our discussion, we had the privilege of hearing you speak about your early career and the challenges you faced during the internship search. Your perspective on being open-minded and curious, and always seeking out what you don't know was truly inspiring. You shed light on the culture at Charles Schwab and what has made you stay there for so many years, and both the Promazo team and our student audience will be excited to learn from you and your experiences.

Attached is a short clip from the interview that we found particularly interesting. The points you made on how you got started in finance after graduating from a school that was maybe not as known for economics and finance were insightful because they show how a student can leverage the talents and skills they have to become successful regardless of their background.

We thank you for your time and meaningful conversation. We look forward to staying in contact with you.

**Comment by carolineradke** [comment]
Clip:

01:09-02:02

**Comment by carolineradke** [comment]
https://docs.google.com/document/d/1B1kV_rAJ8R_9JHYI3IF10hMyALZRqNWIqXonls7V6Nw/edit

Plan
