### ISSUE TITLE
Relationship FU Plan: Carrie Nedrow

### ISSUE THREAD

**Issue by jaahmuhl** [promazo/100k-Mentor-Challenge-Outreach#142]
**User Story / Problem / Details**
The Content Editor is in charge of ensuring the initial relationship we foster with an interviewee does not decay over time for interviewees that we designate as important. As a result we want to follow a process that allows us to interact and build a relationship with the interviewee over time. The final step of the process should be focused on how connect with an interviewee over multiple interactions and over the course of a year.

**Technical Definition of Done**
Complete all steps in the process

**Definition of Ready**
All of the steps in the process have been approved by Brett 

**Process**
- [ ] Review the interview in its entirety 
- [ ] Thank you note to the participant
- [ ] Quick clip (30s) that shows the interviewee some of the raw footage/a particularly interesting part of the discussion
- [ ] ID potential contacts
- [ ] Formulate ask
- [ ] Create a Relationship Action Plan

**Comment by carolineradke** [comment]
Hi Carrie, we wanted to reach out and thank you again for participating in our Executive Interview Series.

During our discussion, we had the privilege of hearing you speak about the importance of building connections as a student, especially with your professors. Your insight into taking risks, being open-minded, and being curious also stood out to us as they relate to the decisions that come with following a "traditional path." Both the Promazo team and our student audience will be excited to learn from you and your experiences.

Attached is a short clip from the interview that we found particularly interesting. The points you made on the importance of building connections through an already trusted source – your professors were intriguing because they show students that regardless of their background, they can become connected and receive support from already trusted professionals.

We thank you for your time and meaningful conversation. We look forward to staying in contact with you.

**Comment by carolineradke** [comment]
Clip:

26:19-26:50

**Comment by carolineradke** [comment]
https://docs.google.com/document/d/1bvni_l9SNsAIaC4Gw2cKwN2OrgkixrcnpkIxeD02PB4/edit

Plan
