### ISSUE TITLE
Long Post-Mandell Crowley

### ISSUE THREAD

**Issue by jaahmuhl** [promazo/100k-Mentor-Challenge-Outreach#204]

**Comment by carolineradke** [comment]
Cut out:

Before 1:24
After 50:23

Intro Clip:

12:08-12:52
(44 sec)

Hello hello everyone (EXCITED AND WITH ENERGY) welcome back to Office Hours. A show about how to make a successful jump from college to young professional life. We know that landing your first job can often be an intimidating, complicated and stressful process, but its not impossible! (UP ENERGRY) And we’re here to help by giving you acccess to some of the brightest minds in business to get their advice for how to build a successful career. Take what you can (short pause), pick what you like and listen for that stroke of brilliance that you can use to help you get hired. I’m Caroline Radke and on the show today is Mandell Crawley, Chief of Human Resources at Morgan Stanley.

Taking risks and overcoming obstacles are spoken about fairly regularly. However, oftentimes, they remain superficial and no proper deep dive is made to understand how to do it and why it is important to do it. Mandell Crawley brings unique insight into why believing in yourself but also working your hardest to get there is important while also focusing on the various obstacles he had to overcome and how this can be reflected in students today who are navigating their early career journeys. 

Transitioning from the west-side of Chicago to Wall Street in New York was a huge cultural difference for Mandell Crawley. However, through his mindset of being passionate, open-minded, and working hard, he succeeded. He started his career at Morgan Stanley as an intern at 17 during high school even though he had no real interest in finance because he thought he would be an educator as a young kid. However, the internship fulfilled a high school requirement so he took advantage of the opportunity. Through this exposure, his curiosity grew and he became more and more interested in the field and in the company.

Mandell Crawley started at Morgan Stanley and never left. A big reason for that is the culture at the company. He credits that to their talent; their people. As CHRO, he never wants to lose sight of that. Morgan Stanley opened its doors in 1935, and during its first year,  the firm handled $1.1 billion in public offerings and private placements—a 24% market share. With strong focus on having a global impact, supporting communities locally and globally, and clear commitments to sustainability, Morgan Stanley is now one of the largest financial services firms in the country, managing more than $1.6 trillion in assets under management.

Today, Mandell Crawley comes to us with valuable insights and advice for young professionals and students who are seeking to stand out. With a unique background and interesting stories about his childhood, early career, geographical transitions, obstacles in life, and more, our discussion with Mandell Crawley is an intriguing one. Now I won't make you wait any longer, let's get into it...

**Comment by carolineradke** [comment]
CAPTION

How do you stand out from everyone else? How do you overcome obstacles in your personal or professional life? How do you adopt a mindset that will lead you to success? Difficult questions seem to be all around us as young professionals, but if you follow the stories and advice that Mandell Crawley, the CHRO at Morgan Stanley, has provided to us today, then you will be on the right track.

**Comment by carolineradke** [comment]
https://drive.google.com/drive/folders/1OgrsZiE1QBQ4GVsomYGgTREySUFCNldZ

podcast intro

**Comment by jaahmuhl** [comment]
@carolineradke We will have to rerecord part of it and add a few sentences on Mandell. Just the Episode Intro needs to be adjusted.

Also i think we should use a better intro clip.
